/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewsRouteRouteImport } from './routes/previews/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewsIndexRouteImport } from './routes/previews/index'
import { Route as PreviewsTooltipRouteImport } from './routes/previews/tooltip'
import { Route as PreviewsToastRouteImport } from './routes/previews/toast'
import { Route as PreviewsTagsInputRouteImport } from './routes/previews/tags-input'
import { Route as PreviewsTabsRouteImport } from './routes/previews/tabs'
import { Route as PreviewsTableRouteImport } from './routes/previews/table'
import { Route as PreviewsSwitchRouteImport } from './routes/previews/switch'
import { Route as PreviewsSpinnerRouteImport } from './routes/previews/spinner'
import { Route as PreviewsSliderRouteImport } from './routes/previews/slider'
import { Route as PreviewsSheetRouteImport } from './routes/previews/sheet'
import { Route as PreviewsSeparatorRouteImport } from './routes/previews/separator'
import { Route as PreviewsSelectRouteImport } from './routes/previews/select'
import { Route as PreviewsRadioGroupRouteImport } from './routes/previews/radio-group'
import { Route as PreviewsPopoverRouteImport } from './routes/previews/popover'
import { Route as PreviewsPaginationRouteImport } from './routes/previews/pagination'
import { Route as PreviewsKbdRouteImport } from './routes/previews/kbd'
import { Route as PreviewsInputGroupRouteImport } from './routes/previews/input-group'
import { Route as PreviewsInputRouteImport } from './routes/previews/input'
import { Route as PreviewsHoverCardRouteImport } from './routes/previews/hover-card'
import { Route as PreviewsFormsRouteImport } from './routes/previews/forms'
import { Route as PreviewsFileUploadRouteImport } from './routes/previews/file-upload'
import { Route as PreviewsFieldRouteImport } from './routes/previews/field'
import { Route as PreviewsEmptyRouteImport } from './routes/previews/empty'
import { Route as PreviewsDropdownMenuRouteImport } from './routes/previews/dropdown-menu'
import { Route as PreviewsDialogRouteImport } from './routes/previews/dialog'
import { Route as PreviewsDatePickerRouteImport } from './routes/previews/date-picker'
import { Route as PreviewsCommandRouteImport } from './routes/previews/command'
import { Route as PreviewsComboboxRouteImport } from './routes/previews/combobox'
import { Route as PreviewsCheckboxRouteImport } from './routes/previews/checkbox'
import { Route as PreviewsCardRouteImport } from './routes/previews/card'
import { Route as PreviewsButtonGroupsRouteImport } from './routes/previews/button-groups'
import { Route as PreviewsButtonRouteImport } from './routes/previews/button'
import { Route as PreviewsBadgeRouteImport } from './routes/previews/badge'
import { Route as PreviewsAvatarRouteImport } from './routes/previews/avatar'
import { Route as PreviewsAttachmentRouteImport } from './routes/previews/attachment'
import { Route as PreviewsAlertRouteImport } from './routes/previews/alert'
import { Route as PreviewsAccordionRouteImport } from './routes/previews/accordion'
import { Route as PreviewsFormsIndexRouteImport } from './routes/previews/forms/index'
import { Route as PreviewsFormsValidationTimingRouteImport } from './routes/previews/forms/validation-timing'
import { Route as PreviewsFormsTagsInputRouteImport } from './routes/previews/forms/tags-input'
import { Route as PreviewsFormsSliderRouteImport } from './routes/previews/forms/slider'
import { Route as PreviewsFormsSelectRouteImport } from './routes/previews/forms/select'
import { Route as PreviewsFormsFileUploadRouteImport } from './routes/previews/forms/file-upload'
import { Route as PreviewsFormsDatePickerRouteImport } from './routes/previews/forms/date-picker'
import { Route as PreviewsFormsCustomControlsRouteImport } from './routes/previews/forms/custom-controls'
import { Route as PreviewsFormsBasicRouteImport } from './routes/previews/forms/basic'
import { Route as PreviewsFormsAsyncValidationRouteImport } from './routes/previews/forms/async-validation'
import { Route as PreviewsFormsArrayFieldsRouteImport } from './routes/previews/forms/array-fields'

const PreviewsRouteRoute = PreviewsRouteRouteImport.update({
  id: '/previews',
  path: '/previews',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewsIndexRoute = PreviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsTooltipRoute = PreviewsTooltipRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsToastRoute = PreviewsToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsTagsInputRoute = PreviewsTagsInputRouteImport.update({
  id: '/tags-input',
  path: '/tags-input',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsTabsRoute = PreviewsTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsTableRoute = PreviewsTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsSwitchRoute = PreviewsSwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsSpinnerRoute = PreviewsSpinnerRouteImport.update({
  id: '/spinner',
  path: '/spinner',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsSliderRoute = PreviewsSliderRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsSheetRoute = PreviewsSheetRouteImport.update({
  id: '/sheet',
  path: '/sheet',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsSeparatorRoute = PreviewsSeparatorRouteImport.update({
  id: '/separator',
  path: '/separator',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsSelectRoute = PreviewsSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsRadioGroupRoute = PreviewsRadioGroupRouteImport.update({
  id: '/radio-group',
  path: '/radio-group',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsPopoverRoute = PreviewsPopoverRouteImport.update({
  id: '/popover',
  path: '/popover',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsPaginationRoute = PreviewsPaginationRouteImport.update({
  id: '/pagination',
  path: '/pagination',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsKbdRoute = PreviewsKbdRouteImport.update({
  id: '/kbd',
  path: '/kbd',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsInputGroupRoute = PreviewsInputGroupRouteImport.update({
  id: '/input-group',
  path: '/input-group',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsInputRoute = PreviewsInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsHoverCardRoute = PreviewsHoverCardRouteImport.update({
  id: '/hover-card',
  path: '/hover-card',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsFormsRoute = PreviewsFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsFileUploadRoute = PreviewsFileUploadRouteImport.update({
  id: '/file-upload',
  path: '/file-upload',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsFieldRoute = PreviewsFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsEmptyRoute = PreviewsEmptyRouteImport.update({
  id: '/empty',
  path: '/empty',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsDropdownMenuRoute = PreviewsDropdownMenuRouteImport.update({
  id: '/dropdown-menu',
  path: '/dropdown-menu',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsDialogRoute = PreviewsDialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsDatePickerRoute = PreviewsDatePickerRouteImport.update({
  id: '/date-picker',
  path: '/date-picker',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsCommandRoute = PreviewsCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsComboboxRoute = PreviewsComboboxRouteImport.update({
  id: '/combobox',
  path: '/combobox',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsCheckboxRoute = PreviewsCheckboxRouteImport.update({
  id: '/checkbox',
  path: '/checkbox',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsCardRoute = PreviewsCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsButtonGroupsRoute = PreviewsButtonGroupsRouteImport.update({
  id: '/button-groups',
  path: '/button-groups',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsButtonRoute = PreviewsButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsBadgeRoute = PreviewsBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsAvatarRoute = PreviewsAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsAttachmentRoute = PreviewsAttachmentRouteImport.update({
  id: '/attachment',
  path: '/attachment',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsAlertRoute = PreviewsAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsAccordionRoute = PreviewsAccordionRouteImport.update({
  id: '/accordion',
  path: '/accordion',
  getParentRoute: () => PreviewsRouteRoute,
} as any)
const PreviewsFormsIndexRoute = PreviewsFormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewsFormsRoute,
} as any)
const PreviewsFormsValidationTimingRoute =
  PreviewsFormsValidationTimingRouteImport.update({
    id: '/validation-timing',
    path: '/validation-timing',
    getParentRoute: () => PreviewsFormsRoute,
  } as any)
const PreviewsFormsTagsInputRoute = PreviewsFormsTagsInputRouteImport.update({
  id: '/tags-input',
  path: '/tags-input',
  getParentRoute: () => PreviewsFormsRoute,
} as any)
const PreviewsFormsSliderRoute = PreviewsFormsSliderRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => PreviewsFormsRoute,
} as any)
const PreviewsFormsSelectRoute = PreviewsFormsSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => PreviewsFormsRoute,
} as any)
const PreviewsFormsFileUploadRoute = PreviewsFormsFileUploadRouteImport.update({
  id: '/file-upload',
  path: '/file-upload',
  getParentRoute: () => PreviewsFormsRoute,
} as any)
const PreviewsFormsDatePickerRoute = PreviewsFormsDatePickerRouteImport.update({
  id: '/date-picker',
  path: '/date-picker',
  getParentRoute: () => PreviewsFormsRoute,
} as any)
const PreviewsFormsCustomControlsRoute =
  PreviewsFormsCustomControlsRouteImport.update({
    id: '/custom-controls',
    path: '/custom-controls',
    getParentRoute: () => PreviewsFormsRoute,
  } as any)
const PreviewsFormsBasicRoute = PreviewsFormsBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => PreviewsFormsRoute,
} as any)
const PreviewsFormsAsyncValidationRoute =
  PreviewsFormsAsyncValidationRouteImport.update({
    id: '/async-validation',
    path: '/async-validation',
    getParentRoute: () => PreviewsFormsRoute,
  } as any)
const PreviewsFormsArrayFieldsRoute =
  PreviewsFormsArrayFieldsRouteImport.update({
    id: '/array-fields',
    path: '/array-fields',
    getParentRoute: () => PreviewsFormsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/previews': typeof PreviewsRouteRouteWithChildren
  '/previews/accordion': typeof PreviewsAccordionRoute
  '/previews/alert': typeof PreviewsAlertRoute
  '/previews/attachment': typeof PreviewsAttachmentRoute
  '/previews/avatar': typeof PreviewsAvatarRoute
  '/previews/badge': typeof PreviewsBadgeRoute
  '/previews/button': typeof PreviewsButtonRoute
  '/previews/button-groups': typeof PreviewsButtonGroupsRoute
  '/previews/card': typeof PreviewsCardRoute
  '/previews/checkbox': typeof PreviewsCheckboxRoute
  '/previews/combobox': typeof PreviewsComboboxRoute
  '/previews/command': typeof PreviewsCommandRoute
  '/previews/date-picker': typeof PreviewsDatePickerRoute
  '/previews/dialog': typeof PreviewsDialogRoute
  '/previews/dropdown-menu': typeof PreviewsDropdownMenuRoute
  '/previews/empty': typeof PreviewsEmptyRoute
  '/previews/field': typeof PreviewsFieldRoute
  '/previews/file-upload': typeof PreviewsFileUploadRoute
  '/previews/forms': typeof PreviewsFormsRouteWithChildren
  '/previews/hover-card': typeof PreviewsHoverCardRoute
  '/previews/input': typeof PreviewsInputRoute
  '/previews/input-group': typeof PreviewsInputGroupRoute
  '/previews/kbd': typeof PreviewsKbdRoute
  '/previews/pagination': typeof PreviewsPaginationRoute
  '/previews/popover': typeof PreviewsPopoverRoute
  '/previews/radio-group': typeof PreviewsRadioGroupRoute
  '/previews/select': typeof PreviewsSelectRoute
  '/previews/separator': typeof PreviewsSeparatorRoute
  '/previews/sheet': typeof PreviewsSheetRoute
  '/previews/slider': typeof PreviewsSliderRoute
  '/previews/spinner': typeof PreviewsSpinnerRoute
  '/previews/switch': typeof PreviewsSwitchRoute
  '/previews/table': typeof PreviewsTableRoute
  '/previews/tabs': typeof PreviewsTabsRoute
  '/previews/tags-input': typeof PreviewsTagsInputRoute
  '/previews/toast': typeof PreviewsToastRoute
  '/previews/tooltip': typeof PreviewsTooltipRoute
  '/previews/': typeof PreviewsIndexRoute
  '/previews/forms/array-fields': typeof PreviewsFormsArrayFieldsRoute
  '/previews/forms/async-validation': typeof PreviewsFormsAsyncValidationRoute
  '/previews/forms/basic': typeof PreviewsFormsBasicRoute
  '/previews/forms/custom-controls': typeof PreviewsFormsCustomControlsRoute
  '/previews/forms/date-picker': typeof PreviewsFormsDatePickerRoute
  '/previews/forms/file-upload': typeof PreviewsFormsFileUploadRoute
  '/previews/forms/select': typeof PreviewsFormsSelectRoute
  '/previews/forms/slider': typeof PreviewsFormsSliderRoute
  '/previews/forms/tags-input': typeof PreviewsFormsTagsInputRoute
  '/previews/forms/validation-timing': typeof PreviewsFormsValidationTimingRoute
  '/previews/forms/': typeof PreviewsFormsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/previews/accordion': typeof PreviewsAccordionRoute
  '/previews/alert': typeof PreviewsAlertRoute
  '/previews/attachment': typeof PreviewsAttachmentRoute
  '/previews/avatar': typeof PreviewsAvatarRoute
  '/previews/badge': typeof PreviewsBadgeRoute
  '/previews/button': typeof PreviewsButtonRoute
  '/previews/button-groups': typeof PreviewsButtonGroupsRoute
  '/previews/card': typeof PreviewsCardRoute
  '/previews/checkbox': typeof PreviewsCheckboxRoute
  '/previews/combobox': typeof PreviewsComboboxRoute
  '/previews/command': typeof PreviewsCommandRoute
  '/previews/date-picker': typeof PreviewsDatePickerRoute
  '/previews/dialog': typeof PreviewsDialogRoute
  '/previews/dropdown-menu': typeof PreviewsDropdownMenuRoute
  '/previews/empty': typeof PreviewsEmptyRoute
  '/previews/field': typeof PreviewsFieldRoute
  '/previews/file-upload': typeof PreviewsFileUploadRoute
  '/previews/hover-card': typeof PreviewsHoverCardRoute
  '/previews/input': typeof PreviewsInputRoute
  '/previews/input-group': typeof PreviewsInputGroupRoute
  '/previews/kbd': typeof PreviewsKbdRoute
  '/previews/pagination': typeof PreviewsPaginationRoute
  '/previews/popover': typeof PreviewsPopoverRoute
  '/previews/radio-group': typeof PreviewsRadioGroupRoute
  '/previews/select': typeof PreviewsSelectRoute
  '/previews/separator': typeof PreviewsSeparatorRoute
  '/previews/sheet': typeof PreviewsSheetRoute
  '/previews/slider': typeof PreviewsSliderRoute
  '/previews/spinner': typeof PreviewsSpinnerRoute
  '/previews/switch': typeof PreviewsSwitchRoute
  '/previews/table': typeof PreviewsTableRoute
  '/previews/tabs': typeof PreviewsTabsRoute
  '/previews/tags-input': typeof PreviewsTagsInputRoute
  '/previews/toast': typeof PreviewsToastRoute
  '/previews/tooltip': typeof PreviewsTooltipRoute
  '/previews': typeof PreviewsIndexRoute
  '/previews/forms/array-fields': typeof PreviewsFormsArrayFieldsRoute
  '/previews/forms/async-validation': typeof PreviewsFormsAsyncValidationRoute
  '/previews/forms/basic': typeof PreviewsFormsBasicRoute
  '/previews/forms/custom-controls': typeof PreviewsFormsCustomControlsRoute
  '/previews/forms/date-picker': typeof PreviewsFormsDatePickerRoute
  '/previews/forms/file-upload': typeof PreviewsFormsFileUploadRoute
  '/previews/forms/select': typeof PreviewsFormsSelectRoute
  '/previews/forms/slider': typeof PreviewsFormsSliderRoute
  '/previews/forms/tags-input': typeof PreviewsFormsTagsInputRoute
  '/previews/forms/validation-timing': typeof PreviewsFormsValidationTimingRoute
  '/previews/forms': typeof PreviewsFormsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/previews': typeof PreviewsRouteRouteWithChildren
  '/previews/accordion': typeof PreviewsAccordionRoute
  '/previews/alert': typeof PreviewsAlertRoute
  '/previews/attachment': typeof PreviewsAttachmentRoute
  '/previews/avatar': typeof PreviewsAvatarRoute
  '/previews/badge': typeof PreviewsBadgeRoute
  '/previews/button': typeof PreviewsButtonRoute
  '/previews/button-groups': typeof PreviewsButtonGroupsRoute
  '/previews/card': typeof PreviewsCardRoute
  '/previews/checkbox': typeof PreviewsCheckboxRoute
  '/previews/combobox': typeof PreviewsComboboxRoute
  '/previews/command': typeof PreviewsCommandRoute
  '/previews/date-picker': typeof PreviewsDatePickerRoute
  '/previews/dialog': typeof PreviewsDialogRoute
  '/previews/dropdown-menu': typeof PreviewsDropdownMenuRoute
  '/previews/empty': typeof PreviewsEmptyRoute
  '/previews/field': typeof PreviewsFieldRoute
  '/previews/file-upload': typeof PreviewsFileUploadRoute
  '/previews/forms': typeof PreviewsFormsRouteWithChildren
  '/previews/hover-card': typeof PreviewsHoverCardRoute
  '/previews/input': typeof PreviewsInputRoute
  '/previews/input-group': typeof PreviewsInputGroupRoute
  '/previews/kbd': typeof PreviewsKbdRoute
  '/previews/pagination': typeof PreviewsPaginationRoute
  '/previews/popover': typeof PreviewsPopoverRoute
  '/previews/radio-group': typeof PreviewsRadioGroupRoute
  '/previews/select': typeof PreviewsSelectRoute
  '/previews/separator': typeof PreviewsSeparatorRoute
  '/previews/sheet': typeof PreviewsSheetRoute
  '/previews/slider': typeof PreviewsSliderRoute
  '/previews/spinner': typeof PreviewsSpinnerRoute
  '/previews/switch': typeof PreviewsSwitchRoute
  '/previews/table': typeof PreviewsTableRoute
  '/previews/tabs': typeof PreviewsTabsRoute
  '/previews/tags-input': typeof PreviewsTagsInputRoute
  '/previews/toast': typeof PreviewsToastRoute
  '/previews/tooltip': typeof PreviewsTooltipRoute
  '/previews/': typeof PreviewsIndexRoute
  '/previews/forms/array-fields': typeof PreviewsFormsArrayFieldsRoute
  '/previews/forms/async-validation': typeof PreviewsFormsAsyncValidationRoute
  '/previews/forms/basic': typeof PreviewsFormsBasicRoute
  '/previews/forms/custom-controls': typeof PreviewsFormsCustomControlsRoute
  '/previews/forms/date-picker': typeof PreviewsFormsDatePickerRoute
  '/previews/forms/file-upload': typeof PreviewsFormsFileUploadRoute
  '/previews/forms/select': typeof PreviewsFormsSelectRoute
  '/previews/forms/slider': typeof PreviewsFormsSliderRoute
  '/previews/forms/tags-input': typeof PreviewsFormsTagsInputRoute
  '/previews/forms/validation-timing': typeof PreviewsFormsValidationTimingRoute
  '/previews/forms/': typeof PreviewsFormsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/previews'
    | '/previews/accordion'
    | '/previews/alert'
    | '/previews/attachment'
    | '/previews/avatar'
    | '/previews/badge'
    | '/previews/button'
    | '/previews/button-groups'
    | '/previews/card'
    | '/previews/checkbox'
    | '/previews/combobox'
    | '/previews/command'
    | '/previews/date-picker'
    | '/previews/dialog'
    | '/previews/dropdown-menu'
    | '/previews/empty'
    | '/previews/field'
    | '/previews/file-upload'
    | '/previews/forms'
    | '/previews/hover-card'
    | '/previews/input'
    | '/previews/input-group'
    | '/previews/kbd'
    | '/previews/pagination'
    | '/previews/popover'
    | '/previews/radio-group'
    | '/previews/select'
    | '/previews/separator'
    | '/previews/sheet'
    | '/previews/slider'
    | '/previews/spinner'
    | '/previews/switch'
    | '/previews/table'
    | '/previews/tabs'
    | '/previews/tags-input'
    | '/previews/toast'
    | '/previews/tooltip'
    | '/previews/'
    | '/previews/forms/array-fields'
    | '/previews/forms/async-validation'
    | '/previews/forms/basic'
    | '/previews/forms/custom-controls'
    | '/previews/forms/date-picker'
    | '/previews/forms/file-upload'
    | '/previews/forms/select'
    | '/previews/forms/slider'
    | '/previews/forms/tags-input'
    | '/previews/forms/validation-timing'
    | '/previews/forms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/previews/accordion'
    | '/previews/alert'
    | '/previews/attachment'
    | '/previews/avatar'
    | '/previews/badge'
    | '/previews/button'
    | '/previews/button-groups'
    | '/previews/card'
    | '/previews/checkbox'
    | '/previews/combobox'
    | '/previews/command'
    | '/previews/date-picker'
    | '/previews/dialog'
    | '/previews/dropdown-menu'
    | '/previews/empty'
    | '/previews/field'
    | '/previews/file-upload'
    | '/previews/hover-card'
    | '/previews/input'
    | '/previews/input-group'
    | '/previews/kbd'
    | '/previews/pagination'
    | '/previews/popover'
    | '/previews/radio-group'
    | '/previews/select'
    | '/previews/separator'
    | '/previews/sheet'
    | '/previews/slider'
    | '/previews/spinner'
    | '/previews/switch'
    | '/previews/table'
    | '/previews/tabs'
    | '/previews/tags-input'
    | '/previews/toast'
    | '/previews/tooltip'
    | '/previews'
    | '/previews/forms/array-fields'
    | '/previews/forms/async-validation'
    | '/previews/forms/basic'
    | '/previews/forms/custom-controls'
    | '/previews/forms/date-picker'
    | '/previews/forms/file-upload'
    | '/previews/forms/select'
    | '/previews/forms/slider'
    | '/previews/forms/tags-input'
    | '/previews/forms/validation-timing'
    | '/previews/forms'
  id:
    | '__root__'
    | '/'
    | '/previews'
    | '/previews/accordion'
    | '/previews/alert'
    | '/previews/attachment'
    | '/previews/avatar'
    | '/previews/badge'
    | '/previews/button'
    | '/previews/button-groups'
    | '/previews/card'
    | '/previews/checkbox'
    | '/previews/combobox'
    | '/previews/command'
    | '/previews/date-picker'
    | '/previews/dialog'
    | '/previews/dropdown-menu'
    | '/previews/empty'
    | '/previews/field'
    | '/previews/file-upload'
    | '/previews/forms'
    | '/previews/hover-card'
    | '/previews/input'
    | '/previews/input-group'
    | '/previews/kbd'
    | '/previews/pagination'
    | '/previews/popover'
    | '/previews/radio-group'
    | '/previews/select'
    | '/previews/separator'
    | '/previews/sheet'
    | '/previews/slider'
    | '/previews/spinner'
    | '/previews/switch'
    | '/previews/table'
    | '/previews/tabs'
    | '/previews/tags-input'
    | '/previews/toast'
    | '/previews/tooltip'
    | '/previews/'
    | '/previews/forms/array-fields'
    | '/previews/forms/async-validation'
    | '/previews/forms/basic'
    | '/previews/forms/custom-controls'
    | '/previews/forms/date-picker'
    | '/previews/forms/file-upload'
    | '/previews/forms/select'
    | '/previews/forms/slider'
    | '/previews/forms/tags-input'
    | '/previews/forms/validation-timing'
    | '/previews/forms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewsRouteRoute: typeof PreviewsRouteRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/previews': {
      id: '/previews'
      path: '/previews'
      fullPath: '/previews'
      preLoaderRoute: typeof PreviewsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previews/': {
      id: '/previews/'
      path: '/'
      fullPath: '/previews/'
      preLoaderRoute: typeof PreviewsIndexRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/tooltip': {
      id: '/previews/tooltip'
      path: '/tooltip'
      fullPath: '/previews/tooltip'
      preLoaderRoute: typeof PreviewsTooltipRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/toast': {
      id: '/previews/toast'
      path: '/toast'
      fullPath: '/previews/toast'
      preLoaderRoute: typeof PreviewsToastRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/tags-input': {
      id: '/previews/tags-input'
      path: '/tags-input'
      fullPath: '/previews/tags-input'
      preLoaderRoute: typeof PreviewsTagsInputRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/tabs': {
      id: '/previews/tabs'
      path: '/tabs'
      fullPath: '/previews/tabs'
      preLoaderRoute: typeof PreviewsTabsRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/table': {
      id: '/previews/table'
      path: '/table'
      fullPath: '/previews/table'
      preLoaderRoute: typeof PreviewsTableRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/switch': {
      id: '/previews/switch'
      path: '/switch'
      fullPath: '/previews/switch'
      preLoaderRoute: typeof PreviewsSwitchRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/spinner': {
      id: '/previews/spinner'
      path: '/spinner'
      fullPath: '/previews/spinner'
      preLoaderRoute: typeof PreviewsSpinnerRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/slider': {
      id: '/previews/slider'
      path: '/slider'
      fullPath: '/previews/slider'
      preLoaderRoute: typeof PreviewsSliderRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/sheet': {
      id: '/previews/sheet'
      path: '/sheet'
      fullPath: '/previews/sheet'
      preLoaderRoute: typeof PreviewsSheetRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/separator': {
      id: '/previews/separator'
      path: '/separator'
      fullPath: '/previews/separator'
      preLoaderRoute: typeof PreviewsSeparatorRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/select': {
      id: '/previews/select'
      path: '/select'
      fullPath: '/previews/select'
      preLoaderRoute: typeof PreviewsSelectRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/radio-group': {
      id: '/previews/radio-group'
      path: '/radio-group'
      fullPath: '/previews/radio-group'
      preLoaderRoute: typeof PreviewsRadioGroupRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/popover': {
      id: '/previews/popover'
      path: '/popover'
      fullPath: '/previews/popover'
      preLoaderRoute: typeof PreviewsPopoverRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/pagination': {
      id: '/previews/pagination'
      path: '/pagination'
      fullPath: '/previews/pagination'
      preLoaderRoute: typeof PreviewsPaginationRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/kbd': {
      id: '/previews/kbd'
      path: '/kbd'
      fullPath: '/previews/kbd'
      preLoaderRoute: typeof PreviewsKbdRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/input-group': {
      id: '/previews/input-group'
      path: '/input-group'
      fullPath: '/previews/input-group'
      preLoaderRoute: typeof PreviewsInputGroupRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/input': {
      id: '/previews/input'
      path: '/input'
      fullPath: '/previews/input'
      preLoaderRoute: typeof PreviewsInputRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/hover-card': {
      id: '/previews/hover-card'
      path: '/hover-card'
      fullPath: '/previews/hover-card'
      preLoaderRoute: typeof PreviewsHoverCardRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/forms': {
      id: '/previews/forms'
      path: '/forms'
      fullPath: '/previews/forms'
      preLoaderRoute: typeof PreviewsFormsRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/file-upload': {
      id: '/previews/file-upload'
      path: '/file-upload'
      fullPath: '/previews/file-upload'
      preLoaderRoute: typeof PreviewsFileUploadRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/field': {
      id: '/previews/field'
      path: '/field'
      fullPath: '/previews/field'
      preLoaderRoute: typeof PreviewsFieldRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/empty': {
      id: '/previews/empty'
      path: '/empty'
      fullPath: '/previews/empty'
      preLoaderRoute: typeof PreviewsEmptyRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/dropdown-menu': {
      id: '/previews/dropdown-menu'
      path: '/dropdown-menu'
      fullPath: '/previews/dropdown-menu'
      preLoaderRoute: typeof PreviewsDropdownMenuRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/dialog': {
      id: '/previews/dialog'
      path: '/dialog'
      fullPath: '/previews/dialog'
      preLoaderRoute: typeof PreviewsDialogRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/date-picker': {
      id: '/previews/date-picker'
      path: '/date-picker'
      fullPath: '/previews/date-picker'
      preLoaderRoute: typeof PreviewsDatePickerRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/command': {
      id: '/previews/command'
      path: '/command'
      fullPath: '/previews/command'
      preLoaderRoute: typeof PreviewsCommandRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/combobox': {
      id: '/previews/combobox'
      path: '/combobox'
      fullPath: '/previews/combobox'
      preLoaderRoute: typeof PreviewsComboboxRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/checkbox': {
      id: '/previews/checkbox'
      path: '/checkbox'
      fullPath: '/previews/checkbox'
      preLoaderRoute: typeof PreviewsCheckboxRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/card': {
      id: '/previews/card'
      path: '/card'
      fullPath: '/previews/card'
      preLoaderRoute: typeof PreviewsCardRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/button-groups': {
      id: '/previews/button-groups'
      path: '/button-groups'
      fullPath: '/previews/button-groups'
      preLoaderRoute: typeof PreviewsButtonGroupsRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/button': {
      id: '/previews/button'
      path: '/button'
      fullPath: '/previews/button'
      preLoaderRoute: typeof PreviewsButtonRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/badge': {
      id: '/previews/badge'
      path: '/badge'
      fullPath: '/previews/badge'
      preLoaderRoute: typeof PreviewsBadgeRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/avatar': {
      id: '/previews/avatar'
      path: '/avatar'
      fullPath: '/previews/avatar'
      preLoaderRoute: typeof PreviewsAvatarRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/attachment': {
      id: '/previews/attachment'
      path: '/attachment'
      fullPath: '/previews/attachment'
      preLoaderRoute: typeof PreviewsAttachmentRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/alert': {
      id: '/previews/alert'
      path: '/alert'
      fullPath: '/previews/alert'
      preLoaderRoute: typeof PreviewsAlertRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/accordion': {
      id: '/previews/accordion'
      path: '/accordion'
      fullPath: '/previews/accordion'
      preLoaderRoute: typeof PreviewsAccordionRouteImport
      parentRoute: typeof PreviewsRouteRoute
    }
    '/previews/forms/': {
      id: '/previews/forms/'
      path: '/'
      fullPath: '/previews/forms/'
      preLoaderRoute: typeof PreviewsFormsIndexRouteImport
      parentRoute: typeof PreviewsFormsRoute
    }
    '/previews/forms/validation-timing': {
      id: '/previews/forms/validation-timing'
      path: '/validation-timing'
      fullPath: '/previews/forms/validation-timing'
      preLoaderRoute: typeof PreviewsFormsValidationTimingRouteImport
      parentRoute: typeof PreviewsFormsRoute
    }
    '/previews/forms/tags-input': {
      id: '/previews/forms/tags-input'
      path: '/tags-input'
      fullPath: '/previews/forms/tags-input'
      preLoaderRoute: typeof PreviewsFormsTagsInputRouteImport
      parentRoute: typeof PreviewsFormsRoute
    }
    '/previews/forms/slider': {
      id: '/previews/forms/slider'
      path: '/slider'
      fullPath: '/previews/forms/slider'
      preLoaderRoute: typeof PreviewsFormsSliderRouteImport
      parentRoute: typeof PreviewsFormsRoute
    }
    '/previews/forms/select': {
      id: '/previews/forms/select'
      path: '/select'
      fullPath: '/previews/forms/select'
      preLoaderRoute: typeof PreviewsFormsSelectRouteImport
      parentRoute: typeof PreviewsFormsRoute
    }
    '/previews/forms/file-upload': {
      id: '/previews/forms/file-upload'
      path: '/file-upload'
      fullPath: '/previews/forms/file-upload'
      preLoaderRoute: typeof PreviewsFormsFileUploadRouteImport
      parentRoute: typeof PreviewsFormsRoute
    }
    '/previews/forms/date-picker': {
      id: '/previews/forms/date-picker'
      path: '/date-picker'
      fullPath: '/previews/forms/date-picker'
      preLoaderRoute: typeof PreviewsFormsDatePickerRouteImport
      parentRoute: typeof PreviewsFormsRoute
    }
    '/previews/forms/custom-controls': {
      id: '/previews/forms/custom-controls'
      path: '/custom-controls'
      fullPath: '/previews/forms/custom-controls'
      preLoaderRoute: typeof PreviewsFormsCustomControlsRouteImport
      parentRoute: typeof PreviewsFormsRoute
    }
    '/previews/forms/basic': {
      id: '/previews/forms/basic'
      path: '/basic'
      fullPath: '/previews/forms/basic'
      preLoaderRoute: typeof PreviewsFormsBasicRouteImport
      parentRoute: typeof PreviewsFormsRoute
    }
    '/previews/forms/async-validation': {
      id: '/previews/forms/async-validation'
      path: '/async-validation'
      fullPath: '/previews/forms/async-validation'
      preLoaderRoute: typeof PreviewsFormsAsyncValidationRouteImport
      parentRoute: typeof PreviewsFormsRoute
    }
    '/previews/forms/array-fields': {
      id: '/previews/forms/array-fields'
      path: '/array-fields'
      fullPath: '/previews/forms/array-fields'
      preLoaderRoute: typeof PreviewsFormsArrayFieldsRouteImport
      parentRoute: typeof PreviewsFormsRoute
    }
  }
}

interface PreviewsFormsRouteChildren {
  PreviewsFormsArrayFieldsRoute: typeof PreviewsFormsArrayFieldsRoute
  PreviewsFormsAsyncValidationRoute: typeof PreviewsFormsAsyncValidationRoute
  PreviewsFormsBasicRoute: typeof PreviewsFormsBasicRoute
  PreviewsFormsCustomControlsRoute: typeof PreviewsFormsCustomControlsRoute
  PreviewsFormsDatePickerRoute: typeof PreviewsFormsDatePickerRoute
  PreviewsFormsFileUploadRoute: typeof PreviewsFormsFileUploadRoute
  PreviewsFormsSelectRoute: typeof PreviewsFormsSelectRoute
  PreviewsFormsSliderRoute: typeof PreviewsFormsSliderRoute
  PreviewsFormsTagsInputRoute: typeof PreviewsFormsTagsInputRoute
  PreviewsFormsValidationTimingRoute: typeof PreviewsFormsValidationTimingRoute
  PreviewsFormsIndexRoute: typeof PreviewsFormsIndexRoute
}

const PreviewsFormsRouteChildren: PreviewsFormsRouteChildren = {
  PreviewsFormsArrayFieldsRoute: PreviewsFormsArrayFieldsRoute,
  PreviewsFormsAsyncValidationRoute: PreviewsFormsAsyncValidationRoute,
  PreviewsFormsBasicRoute: PreviewsFormsBasicRoute,
  PreviewsFormsCustomControlsRoute: PreviewsFormsCustomControlsRoute,
  PreviewsFormsDatePickerRoute: PreviewsFormsDatePickerRoute,
  PreviewsFormsFileUploadRoute: PreviewsFormsFileUploadRoute,
  PreviewsFormsSelectRoute: PreviewsFormsSelectRoute,
  PreviewsFormsSliderRoute: PreviewsFormsSliderRoute,
  PreviewsFormsTagsInputRoute: PreviewsFormsTagsInputRoute,
  PreviewsFormsValidationTimingRoute: PreviewsFormsValidationTimingRoute,
  PreviewsFormsIndexRoute: PreviewsFormsIndexRoute,
}

const PreviewsFormsRouteWithChildren = PreviewsFormsRoute._addFileChildren(
  PreviewsFormsRouteChildren,
)

interface PreviewsRouteRouteChildren {
  PreviewsAccordionRoute: typeof PreviewsAccordionRoute
  PreviewsAlertRoute: typeof PreviewsAlertRoute
  PreviewsAttachmentRoute: typeof PreviewsAttachmentRoute
  PreviewsAvatarRoute: typeof PreviewsAvatarRoute
  PreviewsBadgeRoute: typeof PreviewsBadgeRoute
  PreviewsButtonRoute: typeof PreviewsButtonRoute
  PreviewsButtonGroupsRoute: typeof PreviewsButtonGroupsRoute
  PreviewsCardRoute: typeof PreviewsCardRoute
  PreviewsCheckboxRoute: typeof PreviewsCheckboxRoute
  PreviewsComboboxRoute: typeof PreviewsComboboxRoute
  PreviewsCommandRoute: typeof PreviewsCommandRoute
  PreviewsDatePickerRoute: typeof PreviewsDatePickerRoute
  PreviewsDialogRoute: typeof PreviewsDialogRoute
  PreviewsDropdownMenuRoute: typeof PreviewsDropdownMenuRoute
  PreviewsEmptyRoute: typeof PreviewsEmptyRoute
  PreviewsFieldRoute: typeof PreviewsFieldRoute
  PreviewsFileUploadRoute: typeof PreviewsFileUploadRoute
  PreviewsFormsRoute: typeof PreviewsFormsRouteWithChildren
  PreviewsHoverCardRoute: typeof PreviewsHoverCardRoute
  PreviewsInputRoute: typeof PreviewsInputRoute
  PreviewsInputGroupRoute: typeof PreviewsInputGroupRoute
  PreviewsKbdRoute: typeof PreviewsKbdRoute
  PreviewsPaginationRoute: typeof PreviewsPaginationRoute
  PreviewsPopoverRoute: typeof PreviewsPopoverRoute
  PreviewsRadioGroupRoute: typeof PreviewsRadioGroupRoute
  PreviewsSelectRoute: typeof PreviewsSelectRoute
  PreviewsSeparatorRoute: typeof PreviewsSeparatorRoute
  PreviewsSheetRoute: typeof PreviewsSheetRoute
  PreviewsSliderRoute: typeof PreviewsSliderRoute
  PreviewsSpinnerRoute: typeof PreviewsSpinnerRoute
  PreviewsSwitchRoute: typeof PreviewsSwitchRoute
  PreviewsTableRoute: typeof PreviewsTableRoute
  PreviewsTabsRoute: typeof PreviewsTabsRoute
  PreviewsTagsInputRoute: typeof PreviewsTagsInputRoute
  PreviewsToastRoute: typeof PreviewsToastRoute
  PreviewsTooltipRoute: typeof PreviewsTooltipRoute
  PreviewsIndexRoute: typeof PreviewsIndexRoute
}

const PreviewsRouteRouteChildren: PreviewsRouteRouteChildren = {
  PreviewsAccordionRoute: PreviewsAccordionRoute,
  PreviewsAlertRoute: PreviewsAlertRoute,
  PreviewsAttachmentRoute: PreviewsAttachmentRoute,
  PreviewsAvatarRoute: PreviewsAvatarRoute,
  PreviewsBadgeRoute: PreviewsBadgeRoute,
  PreviewsButtonRoute: PreviewsButtonRoute,
  PreviewsButtonGroupsRoute: PreviewsButtonGroupsRoute,
  PreviewsCardRoute: PreviewsCardRoute,
  PreviewsCheckboxRoute: PreviewsCheckboxRoute,
  PreviewsComboboxRoute: PreviewsComboboxRoute,
  PreviewsCommandRoute: PreviewsCommandRoute,
  PreviewsDatePickerRoute: PreviewsDatePickerRoute,
  PreviewsDialogRoute: PreviewsDialogRoute,
  PreviewsDropdownMenuRoute: PreviewsDropdownMenuRoute,
  PreviewsEmptyRoute: PreviewsEmptyRoute,
  PreviewsFieldRoute: PreviewsFieldRoute,
  PreviewsFileUploadRoute: PreviewsFileUploadRoute,
  PreviewsFormsRoute: PreviewsFormsRouteWithChildren,
  PreviewsHoverCardRoute: PreviewsHoverCardRoute,
  PreviewsInputRoute: PreviewsInputRoute,
  PreviewsInputGroupRoute: PreviewsInputGroupRoute,
  PreviewsKbdRoute: PreviewsKbdRoute,
  PreviewsPaginationRoute: PreviewsPaginationRoute,
  PreviewsPopoverRoute: PreviewsPopoverRoute,
  PreviewsRadioGroupRoute: PreviewsRadioGroupRoute,
  PreviewsSelectRoute: PreviewsSelectRoute,
  PreviewsSeparatorRoute: PreviewsSeparatorRoute,
  PreviewsSheetRoute: PreviewsSheetRoute,
  PreviewsSliderRoute: PreviewsSliderRoute,
  PreviewsSpinnerRoute: PreviewsSpinnerRoute,
  PreviewsSwitchRoute: PreviewsSwitchRoute,
  PreviewsTableRoute: PreviewsTableRoute,
  PreviewsTabsRoute: PreviewsTabsRoute,
  PreviewsTagsInputRoute: PreviewsTagsInputRoute,
  PreviewsToastRoute: PreviewsToastRoute,
  PreviewsTooltipRoute: PreviewsTooltipRoute,
  PreviewsIndexRoute: PreviewsIndexRoute,
}

const PreviewsRouteRouteWithChildren = PreviewsRouteRoute._addFileChildren(
  PreviewsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewsRouteRoute: PreviewsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
